# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import numpy as np

def fib(n):
    F = np.array([
        [0, 1],
        [1, 1]
    ])
    x = np.array([
        [0],
        [1]
    ])
    return np.dot(np.linalg.matrix_power(F,n),x)[1]

s=0
i=0
f=1
while f < 4000000:
    s += ( f % 2 ) * f
    i += 1
    f = fib(i)

print(s)

#Completed on Wed, 21 Oct 2020, 13:37